### ISSUE TITLE
Instructions for testing with kitti data

### ISSUE THREAD

**Issue by hengwangzhao** [chrischoy/FCGF#10]
Thanks for your work!
I have run the demo code and visualized the features. However, I don't know how to test with kitti odometry data. Could you give some instructions for running /scrips/test_kitti ?

**Comment by chrischoy** [comment]
Hi Hengwang,

I'm under a bit of load. Could this wait for few weeks?

**Comment by hengwangzhao** [comment]
Okay, thank you!

**Comment by AndreiBarsan** [comment]
Hello, do you happen to have any updates on this? I believe that the provided model checkpoints are missing their corresponding `config.json` files, so if you could post them it would be extremely helpful.

**Comment by AndreiBarsan** [comment]
@hengwangzhao I know this response is a couple of months after your post, but I was able to run this by kicking off a KITTI training job to generate a `config.json`, and then modifying it to load the downloaded checkpoint. See #12.

(This included (1) creating a directory, (2) putting the config.json in it, (3) putting a symlink to the desired checkpoint in the directory called `checkpoint.pth`, (4) modifying the config.json so its `save_dir` points to its own directory, (5) running the KITTI test script.)
