### ISSUE TITLE
Batch indices on the last column.

### ISSUE THREAD

**Issue by XuyangBai** [chrischoy/FCGF#16]
Hi @chrischoy ,  I think this [line](https://github.com/chrischoy/FCGF/blob/d6e3c1b7502119b7a533169345fb55968e4995f0/util/misc.py#L84) should be 
```python
coords = np.hstack([np.zeros((len(coords), 1)), coords])
# coords = np.hstack([coords, np.zeros((len(coords), 1))])
```
as you have updated the `MinkowskiEngine` to version 0.4

**Comment by chrischoy** [comment]
Thanks for submitting the issue!
