### ISSUE TITLE
Model zoo link for Kitti 20cm is missing.

### ISSUE THREAD

**Issue by XuyangBai** [chrischoy/FCGF#2]
Hi, Thank you so much for your sharing. I found that the link to the model on Kitti dataset 20cm voxel size is missing. Could you please check it ?

**Comment by chrischoy** [comment]
Ah, thanks for letting me know. I'll update the readme

**Comment by chrischoy** [comment]
Just copied the weights again. Thanks for reporting the issue again and closing for good.
