### ISSUE TITLE
The Color Map of Features

### ISSUE THREAD

**Issue by MyEvolution** [chrischoy/FCGF#21]
First of all, thanks for sharing the code. This is an amazing project. Now I meet some problem. 
I do some test on real-world data using the default weight(which are downloaded from [here](https://node1.chrischoy.org/data/publications/fcgf/2019-09-18_14-15-59.pth)).  The result seems bad. The colors in the same places should be the same, but they are very different. 
![](https://evolution-video.oss-cn-beijing.aliyuncs.com/images/feature_comp.png).
What I do to the colored mesh is a voxel clustering simplification, because I need to download it to see. And I don't think this influences the visualization result. Is the defualt weight not right for general scene? Should I retrain the model using kitti dataset?
Thanks again!

**Comment by chrischoy** [comment]
The datasets that we used on this paper are all real-world datasets. 3DMatch is RGBD scans of indoor scenes and KITTI is LIDAR scans of European urban streets.

From what I see, the scans look very dense and seems more similar to the 3DMatch dataset.

In general, you need to use the right voxel size and follow the right configuration the network is trained for. For instance, 5cm --> voxel size 0.05 when point clouds are embedded in a metric space where 1 is 1 meter. Also, set --normalize_feature True if you use normalized feature.

I personally saw that the network pretrained weights work pretty nicely on other datasets, so you might want to check whether you are loading the correct weights and whether the configurations are correct.

Please let me know if you have more questions.

**Comment by MyEvolution** [comment]
> The datasets that we used on this paper are all real-world datasets. 3DMatch is RGBD scans of indoor scenes and KITTI is LIDAR scans of European urban streets.
> 
> From what I see, the scans look very dense and seems more similar to the 3DMatch dataset.
> 
> In general, you need to use the right voxel size and follow the right configuration the network is trained for. For instance, 5cm --> voxel size 0.05 when point clouds are embedded in a metric space where 1 is 1 meter. Also, set --normalize_feature True if you use normalized feature.
> 
> I personally saw that the network pretrained weights work pretty nicely on other datasets, so you might want to check whether you are loading the correct weights and whether the configurations are correct.
> 
> Please let me know if you have more questions.

Yes, that is exactly what I missed! Thanks for your comments!
