### ISSUE TITLE
tensor.float16 support?

### ISSUE THREAD

**Issue by SwagJ** [chrischoy/FCGF#23]
Dear Chris, 

Due to my limited GPU memory, I was wondering if MinkowskiEngine support float16 computation? I am getting an error when making model as model.to(dtype=tensor.float16), then I am getting this error. 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
f"Type mismatch input: {input_features.type()} != kernel: {kernel.type()}"
AssertionError: Type mismatch input: torch.cuda.FloatTensor != kernel: torch.cuda.HalfTensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Is that maybe because your pretrained model is in float32? 
Thank you in advance.

**Comment by chrischoy** [comment]
Hi,

Currently, it is not supported. I will add support for it as soon as possible, but it should be sometime next week at the earliest.

**Comment by SwagJ** [comment]
Thanks a lot.
