### ISSUE TITLE
Problem with Kitti trainning on Leonhard cluster from MinkowskiEngine

### ISSUE THREAD

**Issue by SwagJ** [chrischoy/FCGF#24]
Dear Chris, 

In Leonhard cluster, during code run, an error occurs which I didn't come across when running code locally. Specifically in this line:https://github.com/StanfordVL/MinkowskiEngine/blob/a0a8ce3ac6aab1e3107a057ff9ec3394087ade6c/MinkowskiEngine/MinkowskiConvolution.py#L86. 

I have also attached the full log for this error. 
[lsf.o5456313.txt](https://github.com/chrischoy/FCGF/files/4392627/lsf.o5456313.txt)

**Comment by chrischoy** [comment]
It is compile with --cpu_only while it could access GPU during runtime.

It happens when you compile it on a server without GPU, but run it on a node with GPU.

**Comment by SwagJ** [comment]
Dear Chris, 

Thanks for your explanation. Our cluster is a GPU cluster. I guess somehow Minkowski failed to detect GPU?

**Comment by chrischoy** [comment]
It uses `torch.cuda.is_available()`. https://github.com/StanfordVL/MinkowskiEngine/blob/master/setup.py#L52

If it fails, it adds `--cpu_only` flag during installation.
Did you happen to install it on the head node without CPU?

**Comment by SwagJ** [comment]
I see. I think I know where the problem is. Thanks a lot for your help.
