### ISSUE TITLE
can't find the demo script

### ISSUE THREAD

**Issue by wookiekim** [chrischoy/FCGF#27]
The script `visualization_demo.py` does not seem to be in the repository.
Can you check?

Thank you!

**Comment by preethamam** [comment]
Even I am facing the same issue. Where is visualization_demo.py?

**Comment by SergioRAgostinho** [comment]
https://github.com/chrischoy/FCGF/blob/e58046c434b7dd455ba793ff598745fd188516ea/demo.py

It was removed and it might be out-of-date.

**Comment by chrischoy** [comment]
The demo script was added back and closing the issue.
