### ISSUE TITLE
Question about downsampling

### ISSUE THREAD

**Issue by lombardm** [chrischoy/FCGF#29]
Hi,
first of all thank you for sharing your code and for your inspiring work. I'm recently diving into it and I would like to ask you a question. I see that you perform a downsampling by dividing each point by the voxel size. Moreover, you claim in your paper that "As the input to the network requires unique coordinates C and corresponding features F, we first downsample the input point cloud". I'm missing the meaning of this and I cannot understand why you do such normalization of the data by dividing all points by the voxel size. If you can elaborate just a bit more this step it could be really helpful! Nevertheless, in the end we still have one 32-dimensional feature per point of our pointcloud or do we not? Thanks and sorry for my bad understanding!

Thanks again, and have a nice day
Marco

**Comment by chrischoy** [comment]
Hi Marco, dividing the points with voxel size is simply to discrete coordinates.

The voxel down sampling is a common technique used to extract features densly. For example, for hand designed FPFH feature extraction, 5cm downsampling is first used before actual feature extraction. This gives bounds on the number of neighbors a point has and also can handle the difference in density easily. For example, points close to the camera tend to have very dense points, whereas points far away from the camera tend to be sparser. Down sampling is a good method for normalizing the number of points in a unit space.

In sum, before the voxel dow sampling, a point cloud could have a region where there are too many points per voxel and we only need one feature per voxel and thus we downsample the points to guarantee that we have one point per voxel.

**Comment by lombardm** [comment]
Thank you for the answer Christopher, now it is more clear! I close the issue. 
Have a nice day
