### ISSUE TITLE
Bug in sample_random_trans() function

### ISSUE THREAD

**Issue by lppllppl920** [chrischoy/FCGF#31]
Hi Chris,

I saw in your code, sample_random_trans() use np.pi / 4 as the input argument in some dataset classes. However, according to the function definition, it actually should accept the unit of degree instead of radian as the argument. I am afraid this may affect your experiment results in your paper if this is actually the case.

**Comment by chrischoy** [comment]
Thanks for the issue.

Yes, it seems that I didn't apply random rotation for KITTI dataset, https://github.com/chrischoy/FCGF/blob/4cc4b85712d215626005403f44c2c4c0a33ed1df/lib/data_loaders.py#L478

Seems like one could get a slight boost in performance after correctly training it with random augmentation.

**Comment by lppllppl920** [comment]
Thanks!
