### ISSUE TITLE
error when running demo.py

### ISSUE THREAD

**Issue by maorp** [chrischoy/FCGF#37]
Hi, im trying to run demo.py after folllowing the installation instaructions. i get:

  File "demo.py", line 73, in <module>
    demo(config)
  File "demo.py", line 29, in demo
    model = ResUNetBN2C(1, 16, normalize_feature=True, conv1_kernel_size=3, D=3)
  File "/home/ubuntu/FCGF/model/resunet.py", line 38, in __init__
    dimension=D)
TypeError: __init__() got an unexpected keyword argument 'bias'

**Comment by sus17** [comment]
I share the same problem as yours, but it occurs because I can't successfully install MinkowskiEngine v0.5 and just clone the original repository, which lacks the parameter 'bias' in ResUNet. Have you executed 'pip install git+https://github.com/NVIDIA/MinkowskiEngine.git@v0.5' and build its wheel succesfullly?

**Comment by BiaoBiaoLi** [comment]
I think this is because the version has been updated,The corresponding interface has been changed. You can modify it according to the corresponding document of Deep glob registration.

**Comment by sunshineatnoon** [comment]
> I think this is because the version has been updated,The corresponding interface has been changed. You can modify it according to the corresponding document of Deep glob registration.

This works. I made several changes using [this file](https://github.com/chrischoy/DeepGlobalRegistration/blob/master/model/resunet.py) as reference. The [residual_block.py](https://github.com/chrischoy/DeepGlobalRegistration/blob/master/model/residual_block.py) also needs some changes.

**Comment by chrischoy** [comment]
This is ones of the  v0.5 changes in Minkowski Engine. Please install the latest version with

```
pip install MinkowskiEngine
```

**Comment by guanglei96** [comment]
> 



> > I think this is because the version has been updated,The corresponding interface has been changed. You can modify it according to the corresponding document of Deep glob registration.
> 
> This works. I made several changes using [this file](https://github.com/chrischoy/DeepGlobalRegistration/blob/master/model/resunet.py) as reference. The [residual_block.py](https://github.com/chrischoy/DeepGlobalRegistration/blob/master/model/residual_block.py) also needs some changes.

Hello, I've encountered the same problem but it hasn't been solved. Can you tell me what changes have been made? Thank you very much
