### ISSUE TITLE
 Processing unordered point sets

### ISSUE THREAD

**Issue by tuduku** [chrischoy/FCGF#48]
Hi, chrischoy. Thanks a lot for the nice work and code.
I have a question about processing unordered point sets. 
In prior works like Pointnet, due to the unorderedness of point sets, Maxpooling is usually used to promise the stability of extracted descriptors, but I do not find any description about the unordered point sets in the paper. Could you offer me some help?

**Comment by chrischoy** [comment]
Please refer to Choy et al., 4D Spatio Temporal ConvNets, CVPR'19.
