### ISSUE TITLE
Visualization error with segmentation fault

### ISSUE THREAD

**Issue by Essxnce** [chrischoy/FCGF#6]
Hello,
Thank you so much for sharing youse awesome work.
But I have a problem. When I tried to operate demo.py, I got the error like below:

![5_am result](https://user-images.githubusercontent.com/36123302/68082142-72530300-fe5c-11e9-804e-c333ee1d5c33.png)

with the black window like this (sometimes my computer is totally stuck with this situation):
![black](https://user-images.githubusercontent.com/36123302/68082233-7e8b9000-fe5d-11e9-80cb-270bf019f631.png)

For better understanding, my computer's spec is like this:
![system spec](https://user-images.githubusercontent.com/36123302/68082208-19d03580-fe5d-11e9-9244-8f43c5fd24ae.png)

I think it has something to do with my memory usage, but I don't know at all why the error occurred.

**Comment by chrischoy** [comment]
Could you try this again on a computer with large RAM? Possibly open3D segfault that I see quite often.

**Comment by Essxnce** [comment]
I don't have other RAMs, so I just reduced the size of point cloud data which is used in demo, so the sample size reduced about a half, and it works. Thank you for your rapid response !!

By the way, I have an another question, but that question is about the training part. So I closed this issue.

**Comment by chrischoy** [comment]
Okay glad that it worked. Why don't you send me an email if it is not an issue?
