### ISSUE TITLE
CUDA out of memory problem

### ISSUE THREAD

**Issue by Essxnce** [chrischoy/FCGF#7]
Hello,
I have another question, and it is also about a memory problem.
When I proceed training.py, GPU memory problem occurred like this:

![GPU memory problem](https://user-images.githubusercontent.com/36123302/68083921-2612bd80-fe72-11e9-9546-b5f525c88e3d.png)

My GPU is GeForce GTX 1050 Ti, and I don't have a much better GPU.
How can I finish this training?
Is there any method to proceed with this task? (such as adjustment of a hyperparameter setting....)

Thank you in advance.

**Comment by chrischoy** [comment]
https://github.com/chrischoy/FCGF/blob/master/config.py#L23

Could you spend some time going through the code first? :)

**Comment by Essxnce** [comment]
Oh, I am sorry. I'm not familiar with handling code so I cannot see the point well.
It is worked when I set batch size for a smaller one than the original value.
(The learning speed is too low, I guess that is because the spec of my GPU is too bad.)
Thank you for your kind reply.
